# Site settings
name: DubDub
email: viaduct@126.com
author: 吴杰
url: http://viaductooor.github.io/blog
resume_site: https://viaductooor.github.io/blog
github: https://github.com/viaductooor
baseurl: /blog
description: #
meta_description: #
motto: Stay foolish, stay hungry.
banner: #

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: viaductooor

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

